### ISSUE TITLE
dev02 vs pearl

### ISSUE THREAD

**Issue by juripapay** [juripapay/hydronet_parallel#1]
The parallel version runs on dev02 but not on pearl. There are some issues with importing libraries. The conda environment in both cases is identical:

On dev02 the following import produces no error:
from torch_geometric.data import DataListLoader, DataLoader

On pearl there is an error:
>>> from torch_geometric.data import DataLoader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/mnt/beegfs/home/pearl061/.conda/envs/hydronet_test/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

**Comment by juripapay** [comment]
There was a conflict between conda environments. Now the code is running ok.
